// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxodauuojrpbbwldsbdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4b2RhdXVvanJwYmJ3bGRzYmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MzYxODQsImV4cCI6MjA3MTQxMjE4NH0.P706R4f8HmqplT0u50veV5RHo7gvxSTNkk2uFV5aN9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});